### ISSUE TITLE
TODO: features to implement before 0.2.1

### ISSUE THREAD

**Issue by Trinsdar** [GregTech-Intergalactical/GT-4-Reimagined#50]
features for 0.2:

- [x] oil driling rig
- [x] oil wells
- [x] tree harvester
- [x] crop harvester
- [x] pump
- [x] long distance pipes
- [x] quadruple and nonuple fluid pipes
- [x] fluid pipe change to gt6 sloshing system
- [x] slight gui refacotor
- [x] air vent
- [x] scanner
- [ ] replicator
- [x] amp fabricator
- [x] mass fabricator
- [ ] ~recycler~ (may not even add this)
- [x] machine control cover
- [x] shutter cover
- [x] fluid filter cover
- [x] make item filter a cover
- [x] multiblock tanks
- [x] large turbine
- [x] large diesel gen
- [x] cryo distillation tower
- [x] change tools to not be nbt based for the most part.

recipes for 0.2
- [x] arc furnace/macerator recycling
- [x] field gens
- [x] fluid regulators
- [x] air distillation

after 0.2

- [x] fusion
- [x] fission
- [ ] assembly line
- [ ] miner multiblock
- [ ] bedrock miner
- [x] miniature nether portal
- [ ] gt5u circuit line for hard circuit config
- [ ] hp pipes for superheated steam and steam pressurizer
- [x] air valve
- [ ] fluid regulator cover
- [ ] redstone transmitter
- [ ] redstone receiver
- [ ] progress sensor
- [ ] item retriever
